### ISSUE TITLE
API service

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#103]

**Comment by mickverm** [comment]
Hoe ver sta je hiermee?

**Comment by JasperDeSutter** [comment]
Er is al een werkende service, enkel nog models en routes toevoegen.

**Comment by HeinPauwelyn** [comment]
Commit al eens iets. Voeg `#103` toe aan de titel van de commit.

<sup> @JasperDeSutter Check FB group</sup>

**Comment by JasperDeSutter** [comment]
Ik ben dit nu verder aan het uitwerken, samen met de backend (controllers, databaseService).

**Comment by HeinPauwelyn** [comment]
@ExCellRaD ik denk dat af is of niet?

**Comment by JasperDeSutter** [comment]
Er moeten enkel nog functies bij die bepaalde routes aanspreken bij, maar het is voor de rest volledig uitgewerkt.

**Comment by HeinPauwelyn** [comment]
Als het maar dat is, mag het gesloten worden hé. Het bijzonderste is dat dat je een API request kan doen voor wat deze issue betreft dan toch.
