### ISSUE TITLE
Carousel op home aanpassen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#104]
Zie #90 laatste comment en onderstaande foto

![](https://cloud.githubusercontent.com/assets/16222780/21501213/4f822496-cc46-11e6-9973-446c6a23c311.png)

**Comment by JasperDeSutter** [comment]
Dit is beter dan de huidige, maar ga je dit zelf maken? Of heb je al iets bestaand gevonden?

**Comment by HeinPauwelyn** [comment]
Nog niet. Wil wel iets bestaands gebruiken zonder JQuery.

**Comment by HeinPauwelyn** [comment]
Zit dat ook in Angular?

**Comment by ExCellRaD** [comment]
Er zitten geen standaard componenten in angular. Wat we wel hebben is https://valor-software.com/ng2-bootstrap/#/  Maar daarin zit er niets gelijkaardig.

**Comment by HeinPauwelyn** [comment]
Ah wij _(ik en @michielzyde)_  wisten dat niet dat je dat gebruikte ipv de native bootstrap. Daarom het ik de native bootstrap gebruikt voor die carousel.

**Comment by ExCellRaD** [comment]
Inderdaad css classen zijn enkel voor css styles nu. Als je iets wilt van bootstrap component is dat ofwel met een tag (zoals `<carousel>`) of met static directives (zoals `dropdownMenu `).
Ik heb het toch al een aantal keren gelinkt? +Michiel heeft het er zelf ingestoken.

**Comment by HeinPauwelyn** [comment]
Had je of @michielzyde beter eens uigelegd in een issue hoe die dat werkte. Ik had nog nooit gehoord van die ng2-bootstrap. Dacht dat dat hetzelfde was als native bootstrap.
