### ISSUE TITLE
Ingelogd navbar

### ISSUE THREAD

**Issue by ExCellRaD** [WatchFriends/Web#105]
### functionaliteit
- link naar profile
- username en profile picture tonen
- knop uitloggen
- login/register knoppen vervangen indien aangemeld

### benodigdheden:

- [x] profile page @michielzyde96 
- [x] auth-service ingelogd opvragen
- [x] auth-service user opvragen
- [ ] profile picture backend (user model en afbeelding bestand)

**Comment by HeinPauwelyn** [comment]
Profiel foto zou ik niet tonen in de navbar aangezien die foto te klein is. Zie icoon in navbar van GitHub. Vind dat overbodig om die foto in te laden als je toch bijna niets kan zien. Ik zou het houden bij de naam.

**Comment by michielzyde96** [comment]
Ik werk vandaag de profilepage af @JasperDeSutter
