### ISSUE TITLE
Search backend

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#106]
Of zullen we het rechtstreeks doen met TMDb?

**Comment by ExCellRaD** [comment]
Alles moet via zeker backend passeren (clients hebben geen tmdb api keys), maar van daaruit mag het idd gewoon rechtstreeks.

**Comment by HeinPauwelyn** [comment]
Nee ik zal eens nog eens Googlen op de backend om dan een API request te doen naar TMDb. :laughing: :rofl: :smile: :wink:
