### ISSUE TITLE
Geëncrypteerde en tijdelijke tokens per device

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#107]
- [x] Tokens vervalen na 6 maanden niet gebruikt
- [x] Nieuwe token genereren voor nieuwe gebruikers
- [x] Nieuwe token genereren voor vervallen tokens
- [x] 1 token per toestel
- [ ] Duplicatie ckeck
- [ ] Afmelden moet coockie met token verwijderen
- [ ] Encryptie token
- [ ] Log off on all devices

------------------------

**Verouderd:** Er moet voor de Android applicatie een token verzonden worden voor te weten wie er aangemeld is voor de juiste data te gaan opslaan voor te series te volgen, achievements te krijgen of profiel pagina.

1. Moet dit nog geïmplementeerd worden op de backend?
   - Indien ja door wie en wanneer. Ken jezelf toe aan deze issue.
   - Indien nee zal ik wel voor kijken.
2. Is er al iemand me bezig?
   - Indien ja door wie en wanneer. Ken jezelf toe aan deze issue en doe maar voort.
   - Indien nee zal ik wel voor kijken.

Zie ook: https://github.com/WatchFriends/Android/issues/163

**Comment by ExCellRaD** [comment]
Bij een succesvolle login worden tokens gegenereerd en opgeslagen in de database. Deze krijg je dan direct mee als response (`response = { user: ... token: ...}`).

**Comment by ExCellRaD** [comment]
Dit moet wel nog wat verder uitgewerkt worden (mss met een package) om betere keys te maken met encryptie. En eventueel wat caching zodat er niet iedere keer een database request nodig is.

**Comment by HeinPauwelyn** [comment]
Oke zal morgen daarvoor kijken om dan ook de following en watched te gaan opslaan en dan pas #26.

**Comment by HeinPauwelyn** [comment]
Het moet ongeveer zo iets zijn:

> Generally speaking, authentication works by sending a token to your device, that you subsequently use when making calls that requires authentication.
>
> Now assuming this is a valid token, the server will accept the request and perform whatever action is associated with that request. And if it's not, it'll throw an error back in the face of the app/website.
>
> Logout on all devices works by taking advantage of this authentication functionality. Simply put, it invalidates all authentication tokens that were issues before Now, (possibly sending a logout request to connected devices first).
> 
> This means that when previously-authenticated clients try to use their authentication tokens to perform an action, the server will simply go "Nope, that token has been invalidated! Log in again please".
>
> **Coments:**
>
>  - _Me:_ I've one more question for you. 1. Has every user a unique token that could used for multiple devices or 2. is that one unique token for each device and a user got multiple unique tokens
>
> - _Answerer:_ Usually every device has a unique token. Otherwise you wouldn't be able to identify devices, and it would make it a lot more insecure to use the same token for all devices. If the token was leaked without your knowledge, someone else could be impersonating you, because you'd only have 1 unique token.
> 
> - _Me:_ What I've expected. But how do you know that the device that will authenticate is always the same with a unique code. I mean what if the token of device A is stolen and the token will be used for authenticate device B?
>
> - _Answerer:_ Well, you don't. And that's when the user would use the 'Invalidate all tokens'-functionality.
>
> <sup>Source: <a href="http://softwareengineering.stackexchange.com/questions/332737/log-off-system-on-all-devices">Software Engineering (Log off system on all devices)</a>

**Comment by HeinPauwelyn** [comment]
Indien je de code eens wilt bekijken die ik nu al een beetje aangepast heb en reacties hebt: bekijk en reageer zeker op deze commit: https://github.com/WatchFriends/Web/commit/fbbca4384cf98b558e2f5f948eb0bb1edd37255e

**Comment by HeinPauwelyn** [comment]
@WatchFriends/backend-webdevelopers Wat denk je van bovenstaande comment?

**Comment by mickverm** [comment]
https://github.com/WatchFriends/Web/pull/115#issuecomment-269977422

**Comment by HeinPauwelyn** [comment]
@WatchFriends/backend-webdevelopers wie heeft er nu al `./backend/controllers/auth.js` gemaakt en hoe werkt het nu? Ik snap er toch niet zoveel van.

**Comment by mickverm** [comment]
@JasperDeSutter hoogstwaarschijnlijk

**Comment by HeinPauwelyn** [comment]
Zit momenteel daarmee een beetje vast door die bug in #125.

**Comment by HeinPauwelyn** [comment]
Kan dit niet doen omdat ik niet weet hoe alles nu werkt.

**Comment by ExCellRaD** [comment]
@HeinPauwelyn 
In de auth controller (functie "successful") wordt de token gegenereerd, deze functie wordt opgeroepen als login of registratie (of FB/google) goed gelukt is. Deze zorgt er ook voor dat er de user en de token worden teruggestuurd in json.
In passport.js (allerlaatste functie) wordt deze gecontroleerd. Deze functie wordt iedere (beveiligde) request opgeroepen, je krijgt de token hier terug van de client.

Wat er nu gebeurd is gewoon 1 token per user, als er al een is wordt die opgestuurd. Dat moet nog aangepast worden, en de token zelf moet nog veiliger (encryptie en langer).

**Comment by ExCellRaD** [comment]
@HeinPauwelyn ging jij dit nog doen? Ik heb bovenstaande comment geschreven om jou te helpen.

**Comment by HeinPauwelyn** [comment]
Wist niet goed hoe dit werkte. Twijfelde aan het gene wat ik aan het doen was. Nu is het wel duidelijker. Merci voor de uitleg.

**Comment by HeinPauwelyn** [comment]
Mag er in de token ook speciale karakters staan zoals `éèàáìíúùóòëäïüÉîÎÊê€$£µ@#|&`

**Comment by ExCellRaD** [comment]
b64token    = 1*( ALPHA / DIGIT /
                       "-" / "." / "_" / "~" / "+" / "/" ) *"="

Dus ik denk het niet. (komt uit https://tools.ietf.org/html/rfc6750)

**Comment by ExCellRaD** [comment]
Als je nog een package wilt gebruiken eventueel https://github.com/jaredhanson/oauth2orize
Dat komt van dezelfde maker van passport, en dus wordt het aangeraden.

**Comment by HeinPauwelyn** [comment]
1. **Heeft het nut om de token geëncrypteerd in de database te steken?**

    ~~Denk het niet omdat het toch random gegenereerd is en dus onvoorspelbaar is. Indien de key gestolen is, moet er toch een nieuwe gegenereerd worden.~~

    Ja, voorkomt dat alle keys gelekt worden indien er is binnengebroken in de database. 

2. **Heeft het zin om de key geëncrypteerd te versturen?**

    Als het geëncrypteerd staat in de databse is dat altijd het geval.

3. **Is er een functie nodig voor een nieuwe key te genereren?**

    Ja, indien een individuele key gelekt is.

    1. **@ExCellRaD:** Zit dit al op de database of kan je dat met de logout functie?
    2. **@michielzyde & @nielsbril:** Is dit toegevoegd of wil je dit toevoegen in de settings?

**Comment by HeinPauwelyn** [comment]
### Belangerijk!!! @ExCellRaD 

4. **Hoe zal je niet geëncrypteerde token gekend zijn?**

    *Ga even voorbeeld nemen van wachtwoorden: Deze worden geëncrypteerd opgeslaan in de database. Het niet geëncrypteerde wachtwoord, is enkel gekend door de gebruiker en wordt opnieuw geëncrypteerd bij het aanmelden.* 

    Neem dit voorbeeld nu voor de tokens. Wie zal de niet geëncrypteerde token (inmiddels 200 karakters) kennen en hoe zal deze verstuurd worden naar de cliënt? 

    Het beste is om de niet geëncrypteerde token te versturen over HTTPS<sup>1</sup>. Maar als je aanmeld wordt de token opgehaald en moet gedecrypteerd worden. Maar een hash (SHA1) kan niet ongedaan worden! Hoe is dit dan mogelijk?

<sub><sup>1</sup> Wachtwoorden worden ook niet geëncrypteerd over het HTTPS protocol na een POST request. De tunnel is gewoon beveiligd.</sub>

**Comment by ExCellRaD** [comment]
Zoals bij het wachtwoord:
user heeft ongeëncrypteerd  ww (token in dit geval)
-> stuur naar server, direct encrypteren
-> check geëncrypteerde versie tegen die van database 
-> gelijk = access, niet gelijk = geen access

**Comment by ExCellRaD** [comment]
Het belangrijkste nu vooral is dat je die andere dingen toevoegt (zoals timeout na x dagen, unieke key per device...) En dat dat er niet 1 key per user is (wat nu wel het geval is)

**Comment by HeinPauwelyn** [comment]
en wat als je nu bv. wilt aanmelden op een andere PC waar uw token niet gekend is? Het enige wat je dan nog dan doen is een geëncrypteerd wachtwoord versturen. Als je dan iets wilt doen dat rechten nodig heeft krijg je een geëncrypteerd token binnen.

**Comment by HeinPauwelyn** [comment]
per device dan ofzo. Dacht dat je dat niet wilde.

**Comment by ExCellRaD** [comment]
> en wat als je nu bv. wilt aanmelden op een andere PC waar uw token niet gekend is?

Gewoon aanmelden? Dat is toch hoe het werkt? Deze krijgt dan ook een token.

**Comment by HeinPauwelyn** [comment]
en als je dan die token nodig hebt op de backedend?

**Comment by ExCellRaD** [comment]
Waarom heb je tokens nodig op de backend? Het dient enkel als autorisatie van de user.

**Comment by HeinPauwelyn** [comment]
1. Hoe ga je dan weten wie wie is?
2. UserID is minder veilig als dit in de url van iemands profiel staat

**Comment by ExCellRaD** [comment]
> Hoe ga je dan weten wie wie is?

via de access token dat hij meegeeft aan de request. (staat in db welke user dit is)

> UserID is minder veilig als dit in de url van iemands profiel staat

Wat heeft dit hiermee te zien? En hoe kun je dat anders oplossen? enkel de id is uniek.

**Comment by HeinPauwelyn** [comment]
Heb eens een tekening gemaakt waarom encryptie zinloos is voor de tokens.

```none
╔══════════╗
║ Database ║
╚════╦═════╝
     ║
     ║ ↑ 2. Geëncrypteerde token
     ║
╔════╩═════╗  3. Geëncrypteerde token →  ╔═════════════╗
║  Server  ╠═════════════════════════════╣ Android app ║
╚════╦═════╝                             ╚═════════════╝
     ║  
     ║ ↓ 1. Niet geëncrypteerde token
     ║
╔════╩═════╗
║ Web  app ║
╚══════════╝
```

1. De gebruiker maakt een account aan op de web app en krijgt een niet geëncrypteerde token. ⚡️ 
2. Deze token wordt geëncrypteerd (SHA1) opgeslaan op de database.
3. De gebruiker wil nu ook aanmelden op de Android app en krijgt een geëncrypteerde token van de server. ⚡️

**Comment by HeinPauwelyn** [comment]
@WatchFriends/backend-webdevelopers

### Gezocht

Chineeshe :cn: (of Belgische :belgium:) vrijwilligers gezocht voor de tokens eens uit te testen. 

**Eisen**

- Windows 10 besturingssysteem
- Google Chrome, Edge of Firefox

**Stappenplan**

- checkout branch `#61-achievements-verkrijgen` &rarr; slechte naam... 😕 
- Server en frontend opstarten (backend hoeft niet in debug mode)
- Aanmelden op site met onderstaande gegevens:
  - *E-mail:* plop13@kabouter.com 
  - *Wachtwoord:* plop
- Daarna eens in de inspector onder Application de cookie `Token` vinden en deze doorsturen naar mij.

**Resultaat** Dit moet een random gegenereerde tekst zijn van 201 karakters

De waarde in uw cookie moet anders zijn dan de mijne.
