### ISSUE TITLE
"Unexpected token E in JSON at position 0" op register pagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#111]
Probeerde te registreren en kreeg deze error

> Unexpected token `E` in JSON at position 0

Heb geen google of facebook gebruikt.

![image](https://cloud.githubusercontent.com/assets/16222780/21577199/ea00bf00-cf52-11e6-807c-1a101363dfcf.png)

**Comment by JasperDeSutter** [comment]
Backend server aanzetten. Dit komt enkel voor als er geen response is.
