### ISSUE TITLE
Feed

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Web#117]
Omdat we socket.io moeten gebruiken stel ik voor dat we een feed maken waarop alle interacties van je vrienden op terecht komen.

Dit heb ik momenteel om de discussie te starten 😛 

````javascript
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var eventsFeedSchema = new Schema({
        userId: String,
        userName: String,
        //follow, unfollow, watch
        event: String,
        params: [{
            friendId: String,
            seriesId: Number,
            seasonId: Number,
            episodeId: Number,
            rating: {type: Number, maxVal: 5}
        }],
        time: Date
    }, {versionKey: false}
);

module.exports = mongoose.model('events', eventsFeedSchema);

/*
* Beginning of feed
*   Historical + socket.io
*
*   examples:
*       Michiel now follows Michiel Zyde
*       Michiel gave The Walking Dead a rating of 5 stars
*       Michiel watched The Walking Dead Season 1 Episode 1 - blablabla
*       Michiel no longer follows The Walking Dead
*       Michiel completed Season 4 of The Walking Dead
* */
````

Edit; ToDo

- [x] Socket.io
    - [ ] OnFriendFollow
    - [ ] OnEpisodeWatch
    - [ ] OnSeriesFollow/Unfollow
    - [ ] OnRating
    - [ ] OnAchievementUnlock
- [x] Model
- [x] SaveToDb
- [x] GetAllFromDbByFriendUserId

**Comment by mickverm** [comment]
https://github.com/WatchFriends/Web/issues/11

**Comment by HeinPauwelyn** [comment]
Voting van series zou ook lukken denk ik #11. Kunnen dan data sturen naar TMDb https://developers.themoviedb.org/3/tv/rate-tv-show

**Comment by mickverm** [comment]
@HeinPauwelyn we hebben momenteel 2 api keys: dat zou willen zeggen dat we 2 maal een rating kunnen geven en daarna deze constant aanpassen als ik het goed begrijp?

Zouden we de ratings beter zelf niet opslaan?

**Comment by HeinPauwelyn** [comment]
Idd nog niet aan gedacht...

**Comment by HeinPauwelyn** [comment]
Wordt de feed opgeslaan in de database?

**Comment by JasperDeSutter** [comment]
Goed idee, dit kan dan een soort notificatie tray worden in de front-end (navbar?). Daar kunnen dan dingen inkomen zoals nieuwe afleveringen die beschikbaar zijn, vrienden die iets bekeken, achievements die je behaalde... (eventueel ook notificaties zoals 'connection lost, reconnecting' en 'logged in successfuly')

**Comment by HeinPauwelyn** [comment]
Was die meldingen al van plan voor de achievements maar kan je idd ook nog doen voor veel andere dingen.

**Comment by HeinPauwelyn** [comment]
@mickverm Hoe ver ben je al daarmee?

**Comment by mickverm** [comment]
@HeinPauwelyn begin ik nu aan

**Comment by HeinPauwelyn** [comment]
@mickverm Kan je al iets committen? **💡 Tip:** voeg #117 aan de titel van de commit.

**Comment by mickverm** [comment]
Ben momenteel het hele eventsysteem aan het herwerken
