### ISSUE TITLE
Series, season en episode paginas

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#118]
- [ ] Series pagina
- [ ] Season pagina met alle episodes. Vind overbodig om hiervoor een apparte pagina te maken zoals in de Android app

API staat al op de server van Niels.

**Comment by mickverm** [comment]
Desnoods kan je binnen een season met tabbladen werken voor elke aflevering ofzo? of zo'n accordion?

**Comment by HeinPauwelyn** [comment]
accordion lijkt me het beste.

**Comment by JasperDeSutter** [comment]
Ik weet niet of je dit bedoelt, maar er zit een in ng2-bootstrap 
https://valor-software.com/ng2-bootstrap/#/accordion

**Comment by HeinPauwelyn** [comment]
Ja dit lijkt me het beste. Moet wel wat mooier uitgewerkt worden de titels enzo...

**Comment by HeinPauwelyn** [comment]
Series is al een beetje gedaan zie #127

**Comment by HeinPauwelyn** [comment]
@mickverm ben je al hiermee bezig?

**Comment by ExCellRaD** [comment]
duplicate #134
