### ISSUE TITLE
Settings pagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#119]
Instellingen maken voor de gebruikers. gelijkaardig met https://github.com/WatchFriends/Android/issues/127

**Comment by michielzyde96** [comment]
Ik zal deze pagina morgen beginnen maken!

**Comment by HeinPauwelyn** [comment]
We zien het. 1 week later en je hebt nog (bijna) niets. 💩

**Comment by michielzyde96** [comment]
@HeinPauwelyn geduld is een mooie deugd, begin er vandaag aan.

**Comment by michielzyde96** [comment]
@WatchFriends/frontend-webdevelopers was er in de backend al een settings pagina voorzien? Indien ja, dan integreer ik de info ervan in het design van de frontend.

**Comment by HeinPauwelyn** [comment]
Denk nog niet.
