### ISSUE TITLE
Bugs op profiel pagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#126]
Problemen op profiel pagina zie issue #96 en PR #113.

**Tip:** Voeg aan de beschrijving van de PR `fixes #126` toe zodat deze issue automatisch gesloten wordt.

**Comment by michielzyde96** [comment]
Na merge met master nog altijd deze problemen, fout zal dus niet in de profile html of scss zitten maar misschien in die shared scss files?

![image](https://cloud.githubusercontent.com/assets/23495460/21615283/24873a50-d1dd-11e6-8a69-c72aa22309b5.png)

**Comment by HeinPauwelyn** [comment]
Kan normaal niet alles moet identiek compiled worden maar ik sluit dat niet uit. Controleer eens als de scss files identiek zijn met de master op GitHub.

Controleer ook eens je output en de sources in de console. Kan je daar ergens een css file zien? Zit die file eens in een [gist](https://gist.github.com/) _(Git based code snippets (of hoe dat je het ook noemt))_.

**Comment by michielzyde96** [comment]
Ik zie een index file staan met daarin heel wat scss code, hierbij een link vanaf gist:
https://gist.github.com/michielzyde96/dac8fc934bcb25c347c72182f258b9a6

**Comment by michielzyde96** [comment]
Net van de master eens alle scss files gekopieerd en Angular zei: nothing changed. Dus deze zijn identiek. Ik weet echt niet wat er scheelt en ga er nu ook niet meer naar zoeken. Zal de search pagina afwerken.

**Comment by mickverm** [comment]
De dubbele scrollbar komt van

````css
body {
    overflow-x: hidden;
}
````

deze is nodig op de home maar zorgt voor bugs op het profiel, zal kijken om dit te fixen

**Comment by michielzyde96** [comment]
Ja ik had dit ook al gevonden en weggedaan maar nog geen resultaat..

**Comment by mickverm** [comment]
vervelend dat er zoveel scss files zijn >.>

**Comment by michielzyde96** [comment]
Dat staat op site.scss en moet veranderen naar home.scss maar hij past het niet toe. Zit dan met een horizontale scrollbar.

**Comment by mickverm** [comment]
waarom doen we niet alles gewoon in se site.scss?

**Comment by michielzyde96** [comment]
Het is gefixt!

**Comment by mickverm** [comment]
lol ik  had het ook net gefixt 😛

**Comment by mickverm** [comment]
Hoe? 😛

**Comment by michielzyde96** [comment]
In home.component.ts iets toegevoegd en dan die overflow-x hidden op de home.component.scss gezet zodat ie dat enkel daar kent
