### ISSUE TITLE
ingelogd blijven

### ISSUE THREAD

**Issue by JasperDeSutter** [WatchFriends/Web#128]
cookie dat user-token bijhoudt om aangemeld te blijven bij opnieuw laden van site.
(en uitlogknop op navbar)
fixes #105

**Comment by michielzyde96** [comment]
@mickverm werkt de login nu?

**Comment by mickverm** [comment]
refresh --> logout

**Comment by michielzyde96** [comment]
Ik kan niet inloggen of registreren, krijg dit te zien
![image](https://cloud.githubusercontent.com/assets/23495460/21647978/b079856c-d29c-11e6-819e-0799d7dc8da2.png)

**Comment by HeinPauwelyn** [comment]
zie #111

**Comment by JasperDeSutter** [comment]
backend aanzetten, dan werkt het allemaal.

**Comment by HeinPauwelyn** [comment]
normaal wel heb zelf nog niet getest omdat backend niet werkt van mij

**Comment by HeinPauwelyn** [comment]
@ExCellRaD is dat af want staat al onder done in projecten

**Comment by JasperDeSutter** [comment]
@mickverm heeft dit weer geopend.
