### ISSUE TITLE
node ./backend/server.js combineren met npm start?

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#130]
Kunnen we de commando's `gulp`, `node ./backend/server.js` en `npm start` niet combineren zodat we enkel nog `npm start` hoeven te gebruiken?

**Comment by mickverm** [comment]
@HeinPauwelyn ik heb een manier gevonden maar die opent dan bijvoorbeeld wel 3 terminals buiten uw editor, hij opent geen 3 terminals binnen uw editor
