### ISSUE TITLE
Config.json op Gist

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#132]
Graag iedereen de Gist forken en indien je extra dingen hebt voor aan te vullen, dit committen op uw fork! In de originele gist, plaats je een comment dat er iets is toegevoegd en dan moet ik manueel alles aanpassen. Niet veel werk bij kleine Gists.

Als je niets te commiten hebt meld het me dan op de originele Gist!

~~Ik wil graag vandaag eens de GitHub Gist uit testen.~~

> Gists are a great way to share your work. You can share single files, parts of files, or full applications. You can access gists at https://gist.github.com.
> 
> Every gist is a Git repository, which means that it can be forked and cloned.

~~Ik zoek dus één iemand om dit mee uit te testen.~~ Link naar repo op Facebook of Slack.

~~@mickverm heb jij zin?~~

**Comment by mickverm** [comment]
sure, wat moet ik doen? 😛

**Comment by HeinPauwelyn** [comment]
Ik heb gisteren een gist gemaakt de link staat op de Facebook groep. Open die en fork deze repo. Kloon hem in uw client en commit iets. starks fotos

**Comment by HeinPauwelyn** [comment]
indien je wilt skypen mijn skypenaam is hein.pauwelyn

**Comment by HeinPauwelyn** [comment]
@michielzyde klaar?

**Comment by mickverm** [comment]
ja, klaar, was gaan eten

**Comment by mickverm** [comment]
Ik heb je stappenplan gevolgd, wat nu? 😛

**Comment by HeinPauwelyn** [comment]
Ben het aan opzoeken wat nu. Als ik je nodig heb, zal ik u wel roepen.

**Comment by HeinPauwelyn** [comment]
Je kan blijkbaar geen PR doen op gists zie: http://stackoverflow.com/questions/8758612/can-i-make-a-pull-request-on-a-gist-on-github

Dit is dan het moment waarop je in een comment zal zeggen dat je iets toegevoegd hebt op de originele gist. Dan moet de eigenaar alles manueel mergen.

**Comment by JasperDeSutter** [comment]
@HeinPauwelyn bekijk de forks eens.

**Comment by HeinPauwelyn** [comment]
Mijn backend werkt eindelijk opnieuw. De originele gist is geüpdate met uw veranderingen. Merci 😄
