### ISSUE TITLE
Property forRoot does not exist on type typeof DropdownModule.

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#140]
Heb hier een probleem gemeld maar heb nog geen antwoord. https://github.com/WatchFriends/Web/pull/129#issuecomment-270341118

> Deze [twee lijnen](https://github.com/WatchFriends/Web/blob/master/frontend/app/app.module.ts#L41) geven een error bij mij:
> 
> ```js
> DropdownModule.forRoot(),
> CollapseModule.forRoot(),
> ```
>
> > Property `forRoot` does not exist on type `typeof DropdownModule`.

**Comment by JasperDeSutter** [comment]
Geen idee, eens npm update?

**Comment by mickverm** [comment]
Wis eens je node_modules en doe npm install? dat fixt meestal alles bij mij 😛

**Comment by HeinPauwelyn** [comment]
Travis geeft geen problemen daarover dus zal wel dat zijn zeker.
