### ISSUE TITLE
Geen PR & Update van master mogelijk

### ISSUE THREAD

**Issue by michielzyde96** [WatchFriends/Web#142]
Ik heb een nieuwe branch aangemaakt genaamd error om daarin de error page aan te maken.
Het is niet mogelijk om een PR te maken of te gaan updaten van de master.

Dit is de melding: 
![image](https://cloud.githubusercontent.com/assets/23495460/21693911/029ad396-d383-11e6-88f4-bbb5a7b3f40f.png)

Hoe komt dit?

**Comment by michielzyde96** [comment]
#124

**Comment by mickverm** [comment]
Heb je per ongeluk eens iets gecommit op de master?

**Comment by michielzyde96** [comment]
![image](https://cloud.githubusercontent.com/assets/23495460/21712243/d3d2d4d4-d3f3-11e6-9edf-d5803380c894.png)

**Comment by michielzyde96** [comment]
Ah toch wel dit hier op de master gesmeten
![image](https://cloud.githubusercontent.com/assets/23495460/21712277/20dfc8ea-d3f4-11e6-8ef5-5e1f6406ba6d.png)
