### ISSUE TITLE
Internal server error when search

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#150]
http://localhost:3000/api/series/search?query=plop geeft dit:

```json
{
    "message": "Our service is temporarily unavailable",
    "status": 500
}
```

**Comment by michielzyde96** [comment]
![image](https://cloud.githubusercontent.com/assets/23495460/21725208/b40c26fc-d437-11e6-954f-52017564e655.png)

**Comment by JasperDeSutter** [comment]
Deze error gebeurd als er een null wordt teruggegeven van api of database (zie jouw eigen PR waarin je dit zelf hebt toegevoegd)
Het probleem hiermee is dat null geen error moet geven aangezien dat het een geldige waarde is. Het wil gewoon zeggen dat er geen waarde gevonden is (geen series gevonden met query plop hier). Deze null-check is dus fout en geeft foute errors terug.
