### ISSUE TITLE
Search Werkt maar half meer na merge van devJasper 

### ISSUE THREAD

**Issue by michielzyde96** [WatchFriends/Web#156]
Na het mergen met de profile API implementatie werkt de search maar half meer.
Er kan maximum 2 keer gezocht worden omdat er via de backend telkens een pagenumber wordt bijgeteld aan de url (zie foto). Bij page number 3 stopt het en na die GET requests is het gedaan, er worden geen GET requests meer gestuurd.

![image](https://cloud.githubusercontent.com/assets/23495460/21748774/d41da68a-d58d-11e6-84e8-b4ef8bfd2f4a.png)

Daarnaast heb ik ook nog fouten in mijn code, @JasperDeSutter los je dit op?
![image](https://cloud.githubusercontent.com/assets/23495460/21748784/1b9e7fd4-d58e-11e6-9ad6-27e688bf9d22.png)

Ik zal tot woensdag niet aan het project werken wegens theorie en labo van front end zelf

**Comment by ExCellRaD** [comment]
Wat is er fout aan die requests?

**Comment by michielzyde96** [comment]
Maximum 3 requests en daarna doet hij niks meer , heeft te maken met die page numbers denk ik.

**Comment by michielzyde96** [comment]
Dan moet je reloaden, kan je terug 3 requests doen en weer niks.

**Comment by michielzyde96** [comment]
Terug hetzelfde: 
![image](https://cloud.githubusercontent.com/assets/23495460/21748802/b38cfec4-d58e-11e6-8a54-4216b12bcdaf.png)

**Comment by ExCellRaD** [comment]
Vreemd, dacht dat ik het goed getest had. Zal het zo rap mogelijk oplossen.

**Comment by ExCellRaD** [comment]
Ik heb et al gevonden 😄

**Comment by michielzyde96** [comment]
Wat was het 👍 ?

**Comment by ExCellRaD** [comment]
page werd niet terug op 0 gezet als er een nieuwe route query binnenkwam.

**Comment by HeinPauwelyn** [comment]
# Series pagina

Deze wekt zelf niet meer.

**Comment by HeinPauwelyn** [comment]
Van mij werkt alles weer terug. Sluiten?

**Comment by ExCellRaD** [comment]
voeg anders fixes toe aan jouw PR #165

**Comment by HeinPauwelyn** [comment]
Ga straks op de master mergen. Je kan dan alles van daar afhalen.
