### ISSUE TITLE
Friends

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Web#159]
Is er al iemand begonnen aan een systeem om vrienden te volgen?
@HeinPauwelyn @ExCellRaD  @JasperDeSutter

**Comment by JasperDeSutter** [comment]
Ik ging ermee beginnen vandaag, samen met de user controller

**Comment by HeinPauwelyn** [comment]
Denk het niet. ik denk wel dat @ExCellRaD al API roetes aangemaakt heeft voor gevolgde vrienden te maken. Zie [Reversions van API roetes wiki](https://github.com/WatchFriends/Web/wiki/API-routes/_compare/594e40072bad6a3bcc22e9f9134aff6beb2244d5...a4d15fd19dfaf27ea54fcd1420798c0f0af03b27)

**PS** Als je zelf API roetes aanmaakt: vul ze dan aan in de wiki [API roetes](https://github.com/WatchFriends/Web/wiki/API-routes)

**Comment by mickverm** [comment]
Ok, ik heb gewoon voor de feed, getFriends nodig die een lijst van alle vrienden teruggeeft 😛

**Comment by HeinPauwelyn** [comment]
zie wiki 😄

**Comment by mickverm** [comment]
ahja ok, gwn een api call doen, ging ik gwn van db halen, maar is feitelijk zelfde

**Comment by HeinPauwelyn** [comment]
eeuh ja een api call.
