### ISSUE TITLE
opnieuw dubbele scrollbar op profiel pagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#161]
![image](https://cloud.githubusercontent.com/assets/16222780/21750326/07842e40-d5b1-11e6-8d82-edcb790c9577.png)

![image](https://cloud.githubusercontent.com/assets/16222780/21750335/30c73da6-d5b1-11e6-9404-223042148e10.png)

**Comment by ExCellRaD** [comment]
Dit komt doordat ik mijn fixen voor de home weer heb doorgevoerd. Ofwel werkt home (en de footer) niet, ofwel de Profile, ik denk dus dat de profile scss aangepast zal moeten worden.

**Comment by HeinPauwelyn** [comment]
Heb het ook al opgemerkt. ofwel het ene of het andere.

**Comment by michielzyde96** [comment]
@HeinPauwelyn ben terug van weggeweest, is dit probleem er nog steeds?

**Comment by ExCellRaD** [comment]
Het is er nog.

**Comment by michielzyde96** [comment]
Ik zal dit sluiten

**Comment by HeinPauwelyn** [comment]
Waarom? Het is ze nog.

**Comment by michielzyde96** [comment]
In commit zijn ze weg

**Comment by michielzyde96** [comment]
Zal bij de settings branche zitten.
