### ISSUE TITLE
FontAwesome weg doen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#164]
FontAwesome werd toegevoegd maar is nog niet gebruikt. Dit doen we weg

---------

<p align="center"><strike><b>Stemmen</b></stike><br/>1. 👍 Font Awesome mag weg<br/>2. 👎  Font Awesome moet blijven<br/>3. 😄 we blijven glyphicons gebruiken<br/>4. 🎉 we veranderen alles naar Font Awesome<br/>5. 😕 Andere optie<br/>6. ❤️ Geen mening</p>

**Comment by mickverm** [comment]
Ofwel veranderen we dus onze fonts naar FontAwesome ofwel doen we deze idd weg 😛

**Comment by HeinPauwelyn** [comment]
glyphicons bevat ook goede iconen FontAwesome bevat er wel meer.

**Comment by mickverm** [comment]
Maar gebruiken we iconen van fontawesome?

**Comment by HeinPauwelyn** [comment]
Vermoed van niet. @mickverm @ExCellRaD @michielzyde @HeinPauwelyn Graag reageren met 👍 als je het gebruikt of met 👎 als je het niet gebruikt op eerste comment van deze issue.

**Comment by HeinPauwelyn** [comment]
@mickverm op **eerste** comment

**Comment by ExCellRaD** [comment]
Iedereen is voor! 🌟
