### ISSUE TITLE
gevolgde series ophalen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#169]
Kan er iemand uitleggen hoe je gevolgde series kan ophalen van de database?

Wil op de explorer pagina een lijst maken met series die aanbevolen voor de gebruiker zie #166

**Comment by ExCellRaD** [comment]
`dbService.getFollowedSeries(userId)`

**Comment by HeinPauwelyn** [comment]
Doe dat maar werkt niet. Krijg continue een lege lijst terug. Heb al 2 series toevegoegd dat ik volg en keert steeds 0 items terug.

**Comment by ExCellRaD** [comment]
```js
getFollowedSeries: (user, cb) =>
        followedSeries.find({user}, {_id: 0, user: 0}).exec(cb),
```
probeer eens die user te vervangen door userId (of weg te laten)

**Comment by ExCellRaD** [comment]
Ik heb dit aangepast maar de changes zaten blijkbaar in geen enkele commit, zal mss per ongeluk niet opgeslaan hebben.
