### ISSUE TITLE
verdedeging

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#171]
Bericht op Leho

>Beste,
>
>U kan het uurrooster voor de presentaties terugvinden bij de documenten.
Indien u op het aangeduide moment niet aanwezig kan zijn, mij gelieve zo snel mogelijk te contacteren.
>
>Er mag aan het project gewerkt worden tot de dag van de eerste presentatie. Dan wordt alles ingediend (excl node_modules) op leho.
>
>mvg Kevin

**Download uurregeling:** [uurregeling 1.xlsx](https://github.com/WatchFriends/Web/files/693662/uurregeling_1.xlsx)

**Datum:** Woensdag 25 januari van 09:00 AM tot 09:25 AM

**Comment by ExCellRaD** [comment]
> Er mag aan het project gewerkt worden tot de dag van de eerste presentatie.

lees: volgende week donderdag indienen.

**Comment by HeinPauwelyn** [comment]
Wist ik al. Verdeding is op woensdag. Download: [uurregeling]((https://github.com/WatchFriends/Web/files/693662/uurregeling_1.xlsx)).

**Comment by michielzyde96** [comment]
Waarom wordt hier zelf een issue van gemaakt?

**Comment by HeinPauwelyn** [comment]
Zodat iedereen dit ging weten. Niet iedereen kijkt op Facebook of op Slack.

**Comment by HeinPauwelyn** [comment]
@michielzyde Ik zie net dat je niet in de uurregeling staat voor frontend. Kopt dat?

**Comment by michielzyde96** [comment]
@HeinPauwelyn  ja maar ik heb een mail gestuurd naar Kevin en het is in orde nu.
