### ISSUE TITLE
Tegen wanneer moesten we indienen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#172]
zie titel voor front- en backend en android?

**Comment by mickverm** [comment]
> **uurregeling presentatie Front / Back**
> _Door Kevin DeRudder Op: 2017-01-05 12:13_
> Beste,
> 
> U kan het uurrooster voor de presentaties terugvinden bij de documenten.
> Indien u op het aangeduide moment niet aanwezig kan zijn, mij gelieve zo snel mogelijk te contacteren.
> 
> Er mag aan het project gewerkt worden tot de dag van de eerste presentatie. Dan wordt alles ingediend (excl node_modules) op leho.

> mvg Kevin

**Comment by HeinPauwelyn** [comment]
Zie net tegen 5 januari:

![image](https://cloud.githubusercontent.com/assets/16222780/21769701/5576557c-d680-11e6-9c65-062c296842a4.png)

Heeft er iemand dit gedaan 😕 🙏 ...

---------

@mickverm zie #171

**Comment by mickverm** [comment]
Hmmm, zijn laatste woord telt I guess?

**Comment by HeinPauwelyn** [comment]
denk het ook. Eerste presentatie is op 19 januari dus moeten dan indienen.

**Comment by ExCellRaD** [comment]
Mss toch nog een mailtje sturen dat we dit niet gezien hebben, en ook al eens indienen dat ze zeker zijn dat we toch iets hebben.

**Comment by HeinPauwelyn** [comment]
Mag je doen.

**Comment by mickverm** [comment]
hoe zit dat met het indienen?
