### ISSUE TITLE
Iconen worden nog niet geüpdate

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#175]
![image](https://cloud.githubusercontent.com/assets/16222780/21773757/890a3db2-d690-11e6-9105-3f729d7f27c1.png)

De icoon ➕ wordt niet geüpdate naar ✔️  als je de serie aan het volgen bent. Frontend is oke. De bug zit op backend.

**Comment by ExCellRaD** [comment]
Wil ik wel oplossen.
