### ISSUE TITLE
Registratie form op home

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#183]
Registratie formulier op Home pagina &rarr; gemakkelijker om nieuwe gebruikers te lokken. 

**💡 Tip:** Maak component zoals van de series.

**Comment by ExCellRaD** [comment]
Het is al een component, het heeft gewoon nog geen selector. Dat toevoegen en het zou moeten werken.

**Comment by michielzyde96** [comment]
Waar zou je deze dan plaatsen? Bovenaan de pagina of ergens in het midden?

**Comment by HeinPauwelyn** [comment]
Bovenaan rechts ofzo

**Comment by michielzyde96** [comment]
Ik zal morgen proberen een deftig registratie form te maken & eventueel login form.

**Comment by ExCellRaD** [comment]
@michielzyde96 gewoon het huidige stijlen, en eventueel nog knop voor profiel afbeelding.

**Comment by HeinPauwelyn** [comment]
Hoeveel ben je wel van plan om op de register te zetten? Ik zou het houden bij volgende zaken:

- voornaam
- achternaam
- e-mail
- 2x wachtwoord

Indien je op register klikt, ga je direct nar je settings om de ontbrekende info aan te vullen.

**Comment by HeinPauwelyn** [comment]
Mss nog een tip voor profiel foto's en degelijke. Drag 'n drop dingen vind ik zeer leuk om te gebruiken als eindgebruiker. Een handige en gratis package die ik gebruik id [Dropzone.JS](http://www.dropzonejs.com/). **Nota:** Is meer iets voor op settings pagina.

**Comment by michielzyde96** [comment]
@HeinPauwelyn dit had ik inderdaad ook in gedachten, Vermeersch en ik moeten straks wel naar een bedrijf voor SBP dus zal pas voor vanavond zijn.

**Comment by michielzyde96** [comment]
Zo zal de login eruit zien:

![image](https://cloud.githubusercontent.com/assets/23495460/22001164/8f2c35f2-dc43-11e6-8002-e50435750245.png)

**Comment by HeinPauwelyn** [comment]
Dat is veel mooier dan nu. 

**💡 Tip:** Maak ook labels aan met de klasse `sr-only`. Dit is beter voor blinden en slechtzienden. Dit is onzichtbaar op het scherm maar zichtbaar voor de screen readers.

```html
<label class="sr-only" for="email">E-mail</label>
<input id="email" placeholder="E-mail" type="email" required/>
```

Idem voor wachtwoord

**Comment by michielzyde96** [comment]
Zo ziet het registratie formulier er uit: ik heb met die sr-only classes gewerkt en zal dit nu ook als component op de home pagina plaatsen.
![image](https://cloud.githubusercontent.com/assets/23495460/22022473/85c35dfe-dcc2-11e6-84d5-3c79994815fe.png)

**Comment by ExCellRaD** [comment]
Er moeten wel nog labels zijn voor de velden (email, password, firstname...) of de placeholders moeten deze values hebben. Nu weet je niet wat waar moet ingevuld worden.

**Comment by HeinPauwelyn** [comment]
Toevallig of niet? John Deere 

![image](https://cloud.githubusercontent.com/assets/16222780/22023021/c3a3f5be-dcc4-11e6-8d5f-bd55009041c0.png)

**Comment by michielzyde96** [comment]
Was met opzet ;)

**Comment by HeinPauwelyn** [comment]
Nog toevaliger is dat we thuis ook een Jhon Deere hebben 😄

**Comment by michielzyde96** [comment]
Geen valtra's of massey?

**Comment by HeinPauwelyn** [comment]
nee ook nog 2 Fiat

**Comment by michielzyde96** [comment]
Register form op de home page ziet er nu zo uit 🔥 
![image](https://cloud.githubusercontent.com/assets/23495460/22024499/7d5e6fac-dcca-11e6-8d57-aaded1f0405c.png)
