### ISSUE TITLE
Other User profile broken

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Web#188]
![image](https://cloud.githubusercontent.com/assets/1834265/22030977/93405118-dcdf-11e6-8895-183688b337ea.png)

**Comment by mickverm** [comment]
Wie heeft er profielcomponent gemaakt?
@ExCellRaD @JasperDeSutter @HeinPauwelyn

**Comment by ExCellRaD** [comment]
Zyde html en css en ik ts.

**Comment by mickverm** [comment]
@ExCellRaD kan jij dan bovenstaande fixen?

**Comment by ExCellRaD** [comment]
De fout komt van de backend, req.params dat ergens geen function is. Dit terzijde, want er moeten nog veranderingen komen.
De frontend code moet nog aangepast worden naar de veranderingen van Hein op  de backend, alle API calls voor user/... zijn vervangen door 1.

**Comment by mickverm** [comment]
ja, req.params is al gefixet dat was zeker 5 seconden werk

**Comment by ExCellRaD** [comment]
Dan heb je toch geen hulp nodig?
> @ExCellRaD kan jij dan bovenstaande fixen? desnoods op mijn branch?

**Comment by mickverm** [comment]
ja maar er zijn meer bugs dan req.params, die voortkomen door het refactoren van iets door @HeinPauwelyn

**Comment by HeinPauwelyn** [comment]
Ik heb idd dingen aangepast op de backend maar dit is nng niet gemerged met fe master fus dat kan het probleem niet zijn

**Comment by HeinPauwelyn** [comment]
Toch wel. 't Zal dat eijn

**Comment by HeinPauwelyn** [comment]
> @mickverm assigned HeinPauwelyn and unassigned mickverm, ExCellRaD, and JasperDeSutter 15 hours ago

Ben momenteel bezig met andere dingen op backend. Zal voor iemand anders zijn.

**Comment by ExCellRaD** [comment]
Ik zal een PR maken die dit fixt vandaag.
