### ISSUE TITLE
Teveel API Requests op Explorer

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Web#190]
![image](https://cloud.githubusercontent.com/assets/1834265/22059725/5dbebf2c-dd6e-11e6-90f2-6843fa54db6e.png)

**Comment by HeinPauwelyn** [comment]
Token aanvragen op TMDb

**Comment by ExCellRaD** [comment]
We zouden dit best tracken in de apiservice (backend) zodat we niet geen requests sturen naar tmdb als we de limiet bereikt hebben. Indien we wel aan de limiet zitten -> gebruik volgende key of timeout tot een key beschikbaar is.

**Comment by HeinPauwelyn** [comment]
Zal dat nog lukken tegen morgen? Hoe meer keys, minder dezelfde key kan aangevraagd kan worden. We hebben nu 2 keys en moest iedereen nog een key aanvragen, hebben we er 5.
