### ISSUE TITLE
Krijg geen token na aanmelden

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#191]
Denk dat afmelden niet werkt zoals het moet.

**Reden:** Als ik mij wil aanmelden, krijg ik niets binnen in de header. Zie screenshot. Soms krijg ik die wel binnen maar als ik me afmeld en opnieuw aanmeld, is het gedaan.

![image](https://cloud.githubusercontent.com/assets/16222780/22061171/0acab766-dd74-11e6-8413-761fdcda2038.png)

Weet er iemand hoe dit komt?

**Comment by ExCellRaD** [comment]
Wat bedoel je met niets? Wat moet er doorgestuurd worden? En wat is er gedaan als je je opnieuw aanmeldt?

**Comment by HeinPauwelyn** [comment]
Als je wilt aanmelden moet er een token verstuurd worden in de `authorization` header. Dit is niet altijd het geval.

**Comment by ExCellRaD** [comment]
En gebeurt dat als er een token is in de localStorage of als er geen is?

**Comment by HeinPauwelyn** [comment]
- Als er geen is, moet er een aangemaakt worden
- localStorage (cookie) moet verzonden worden &rarr; zal vanavond eens uitzoeken. nu bezig met domotica project.
