### ISSUE TITLE
Uncaught, unspecified `error` event  na aanmelden

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#199]
Na aanmelden krijg ik deze error:

> Uncaught, unspecified `error` event. (Incorrect arguments)
> 
> ```none
> Error: Uncaught, unspecified "error" event. (Incorrect arguments)
>     at Function.emit (events.js:163:17)
>     at Query.Model.$wrapCallback (d:\Documenten\WatchFriends\Web\node_modules\mongoose\lib\model.js:3421:13)
>     at d:\Documenten\WatchFriends\Web\node_modules\kareem\index.js:264:21
>     at d:\Documenten\WatchFriends\Web\node_modules\kareem\index.js:127:16
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> ```

Weet er iemand hoe dit komt?

**Comment by ExCellRaD** [comment]
Ja, heb ik al gefixt op mijn branch. Het was een probleem met de tokens.

**Comment by HeinPauwelyn** [comment]
Wil je nu PR aanmaken zodat ik die bug kan oplossen?
