### ISSUE TITLE
PRESENTATIES

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#212]
[Presentatie Frontend versie 1](https://github.com/WatchFriends/Web/files/727136/Presentatie.Frontend.pptx)

**Comment by ExCellRaD** [comment]
Er is maar één presentatie voor back- en front-end, ziet er al goed uit. Misschien nog iets over de gebruikte packages zeggen voor angular en backend? En ook nog iets over hosting/database/tmdb.
Ik zal de documenten dan in orde maken.

**Comment by HeinPauwelyn** [comment]
[Presentatie Frontend en backend versie 2](https://github.com/WatchFriends/Web/files/727569/Presentatie.Frontend.pptx)

**Comment by HeinPauwelyn** [comment]
[Presentatie Frontend versie 2 met commentaar](https://github.com/WatchFriends/Web/files/727627/Presentatie.Frontend.pptx)

**Comment by HeinPauwelyn** [comment]
Oh ja TMDb moet er nog in.

**Comment by michielzyde** [comment]
Sorry gasten dat ik niet aan de presentatie heb meegeholpen maar heb morgen ook examen netwerken en ben vandaag mijn labo's gaan maken, veel tijd ingestoken en nu pas klaar..

**Comment by mickverm** [comment]
Ziet er goed uit
