### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#26]
- [x] Fake data genereren
- [ ] Eventueel database via Amazon of Azure
- [x] Data doorsturen via API

**Comment by HeinPauwelyn** [comment]
Heb dit al :smile: 

![image](https://cloud.githubusercontent.com/assets/16222780/20494284/714e7480-b01c-11e6-9808-07422f2a4921.png)

**Comment by nielsbril** [comment]
waar staat deze nu gehost? kan eventueel zorgen voor een mongodb gratis ;)

**Comment by HeinPauwelyn** [comment]
Momenteel nog localhost en het is fake data.

**Comment by nielsbril** [comment]
ik zorg vandaag nog of morgen voor een publieke mongodb die jullie kunnen gebruiken ;)
