### ISSUE TITLE
MongoDb

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#31]
Is er al een database aangemaakt?

**Comment by nielsbril** [comment]
@HeinPauwelyn ja, kijk eens in de slack bij general ;) Heb het niet hierop willen zetten, omdat er een connectionString bijzit.

**Comment by nielsbril** [comment]
Zorg er aub ook voor dat je die connectionString in config.js niet commit naar github :)

**Comment by HeinPauwelyn** [comment]
Heb dat in een aparte file gestoken en in de `.gitignore` gezet. Iedereen moet dus over dat bestand beschikken. Best ook aan docenten doorgeven dat ze dat bestand kunnen downloaden van LeHo.

**Comment by nielsbril** [comment]
Uitstekend, merci!
