### ISSUE TITLE
Pagina's aanmaken

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#38]
- [ ] alle pagina's aanmaken en CSS

**Comment by HeinPauwelyn** [comment]
Hoe is het daarmee of zijn jullie er nog niet mee begonnen? Indien geval 1, kan je al iets committen _(voeg `#38` toe aan de naam van de commit)_.

**Comment by ExCellRaD** [comment]
Eerst wachten op #70 want deze fixt een aantal zaken ivm app module en de css.
Ik ben al begonnen met inlogpagina, om de authenticatie te kunnen testen.

**Comment by HeinPauwelyn** [comment]
In #70 worden er toch afbeeldingen van achievements gemaakt? Kon je dat niet in een nieuwe PR steken? Ik dacht dat @michielzyde96 daar al mee bezig waren sinds de PR open was _(enkel de achievements he :smile:)_.

**Comment by HeinPauwelyn** [comment]
Hij kon ook nog een nieuwe branch aanmaken en daarop verder werken + issue om te laten weten waarmee hij bezig was.

**Comment by mickverm** [comment]
Best voor elke aparte pagina een issue maken?

**Comment by ExCellRaD** [comment]
> Best voor elke aparte pagina een issue maken?

Done
