### ISSUE TITLE
Veranderen naar Express server

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#49]
Ook zorgen voor:

- [ ] ~~Angular~~
- [ ] ~~Typescript~~
- [ ] MVC benadering

**Comment by HeinPauwelyn** [comment]
Waarom moest je nu perse alles veranderen naar Express? We hadden al een aantal toonbare dingen en nu hebben we niets meer.

**Comment by ExCellRaD** [comment]
Er is nog niets aangepast he? Master is nog compleet hetzelfde...
We mergen pas als het werkt.

**Comment by HeinPauwelyn** [comment]
intusen kunnen we wel niet veel meer doen he als je dan toch alles opnieuw gaat aanpassen. Ik doe geen dingen 2x opnieuw

**Comment by ExCellRaD** [comment]
Alles dat met tmdb api te maken heeft is volledig onafhankelijk, je kan al proberen dat te implementeren. (Series ophalen, doorsturen via controller)
Het enigste dat nu even gaat moeten wachten is de database.

**Comment by HeinPauwelyn** [comment]
hoezo? je gaat daarvoor toch routes moeten voor aanmaken. en trouwens Angular werkt nog niet eens

**Comment by ExCellRaD** [comment]
Ja, maar dat is 1 minuutje werk om aan te passen naar express. Angular is front-end, wat bedoel je?

**Comment by HeinPauwelyn** [comment]
[Milestone 0.2.0](https://github.com/WatchFriends/Web/milestones) is al twee dagen voorbij. het enige wat er wat voorlopig nog kan is achievements ophalen van de database wat nu dor jouw weer niet werkt omdat je alles wilt aanpassen.

**Comment by HeinPauwelyn** [comment]
Ik heb veel zin om deze issue en de pr #50 te sluiten omdat we te veel tijd aan het verliezen zijn

**Comment by HeinPauwelyn** [comment]
We hebben eens nog geen werkende front end website!

**Comment by ExCellRaD** [comment]
Wat is het probleem? Ik maak een verbetering aan wat we hebben zodat we dan minder werk gaan hebben om authenticatie te doen en database aan te spreken, en jij kan nog verder werken aan de api. Er is niets kapot, we gaan niet achteruit.

**Comment by HeinPauwelyn** [comment]
het werkte al dat is het probleem. Als er nu dubbele code tussen zit is dat geen probleem. we zijn nog maar beginners met node he.

**Comment by ExCellRaD** [comment]
+ ik wil ook express omdat het minder werk is voor mij dan om de huidige code te proberen verstaan.

**Comment by HeinPauwelyn** [comment]
Trouwens hoe lang ben je daar al mee bezig?

**Comment by HeinPauwelyn** [comment]
zeg het maar hoor. hoelang moet je nog en hoelang ben je al bezig. je gaan mijn uitbating niet horen indien ik dat moest doen.

**Comment by ExCellRaD** [comment]
Het is al zo goed als af als die bugs er uit zijn.

**Comment by ExCellRaD** [comment]
Het belangrijkste is nu dat ik ook een werkende database krijg, want nu kan ik niet testen. En dat hangt niet af van deze issue/PR.

**Comment by HeinPauwelyn** [comment]
staat op slack

**Comment by ExCellRaD** [comment]
MongoError: failed to connect to server [pf.webtotal.be:27017] on first connect
    at Pool.eventHandler (c:\Users\jaspe\OneDrive\NMCT\WatchFriends\Web\node_modules\mongodb-core\lib\topologies\server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (c:\Users\jaspe\OneDrive\NMCT\WatchFriends\Web\node_modules\mongodb-core\lib\connection\pool.js:271:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
...

**Comment by HeinPauwelyn** [comment]
geen connectie string tonen aub. ge moet die `pf.` weg doen

**Comment by ExCellRaD** [comment]
Er staat geen connectiestring, enkel url van webserver.

**Comment by HeinPauwelyn** [comment]
dat dan ook niet
