### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#53]
To do:

- [ ] Database tabel
- [ ] Gebruiker laten aanmelden en direct zijn gegevens terug sturen (API)
- [ ] ...

Welke tabellen zullen er nodig zijn? Indien er een te kort is, graag zelf toevoegen aan deze lijst met uw naam erbij:

@heinpauwelyn

- Wachtwoord &rarr; one-way encryptie
- Key voor wachtwoord te hashen
- Aantal mislukte pogingen voor aanmelden
- Tijd tot wanneer hij geblokkeerd is indien hij vijf keer een verkeerd wachtwoord invulde.
- Gebruikersnaam
- Profiel foto
- ID

**Comment by JasperDeSutter** [comment]
Er zitten al een paar handige scripts voor autorisatie in de models folder, ik heb die gemaakt om mongoose te leren.

**Comment by HeinPauwelyn** [comment]
Zullen we dat nog onder milestone 0.2.0 zetten of is dit al voor 0.3.0? Vind het wel vervelend omdat we nog eens geen deftige UI hebben.

**Comment by ExCellRaD** [comment]
Het is een pak werk, ik denk dat we het best houden voor 0.3.
