### ISSUE TITLE
Afbeeldingen maken voor achievements

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#59]
Afbeeldingen maken voor de achievements met Illustrator, Paint of wat dan ook.

Welke achievements zijn er?

| Naam          | Beschrijving            | 
| ------------- | ----------------------- | 
| Follower      | Volg `x` series         | 
| Watcher       | Bekijk `x` series       |
| Friends       | Heb `x` vrienden        |

Zelf ideeën? Zeker toevoegen

Types:

| Type naam | Kleur   |
| --------- | ------- |
| Brons     | <img src="https://cloud.githubusercontent.com/assets/16222780/20967540/50fed736-bc80-11e6-89bb-2320ab66e314.png" width="15" height="15"/> #D1A684 |
| Zilver    | <img src="https://cloud.githubusercontent.com/assets/16222780/20967584/833d44b2-bc80-11e6-8ec1-0fc40640daff.png" width="15" height="15"/> #B4B8BC |
| Goud      | <img src="https://cloud.githubusercontent.com/assets/16222780/20967609/a5b06bb4-bc80-11e6-83f8-7ed84da23e1f.png" width="15" height="15"/> #FFCC01 |

url van de afbeeldingen:

<pre>`images/${this.name}${type}.png`</pre>

<sup>**P.S.:** PNG bevat transparantie.</sup>

**Comment by michielzyde96** [comment]
Dit is hoe het eruit zou zien met de achievements, laat weten wat je ervan vind!
Ik ben ook nog aan het denken aan meer achievements aangezien we niet met friends werken maar met followers, iemand nog ideetjes voor mogelijke achievements (x aantal minuten getrackt, x aantal seasons volledig bekeken, ...)

![image](https://cloud.githubusercontent.com/assets/23495460/21115484/ba796e62-c0b1-11e6-84ad-6bc85211cfca.png)

**Comment by HeinPauwelyn** [comment]
Nice goede afbeeldingen :+1: 

Ik zie dat je met 4 statussen wilt werken? Blauw, brons, zilver en goud. Is er een reden waarom je blauw hebt toegevoegd?

Mss nog volgende melding toevoegen en de kleur van de cirkel gelijk zetten met de kleur van de achievement en het zwarte gedeelte, een paar pixels smaller maken. Is iets te fel aanwezig.

> <p align="center"><b>progress till next achievement:</b><br/>6/10</p>

Voor een project van web in het eerste jaar heb ik SVG gebruikt voor een interactieve* afbeelding te maken. Mss kunnen we dit opnieuw gebruiken maar nu voor de achievements.

<sup>* Interactief was gewoon erover hoveren kreeg je een highlicht kleur en erop klikken was meer info.</sup>

Staat de Illustrator of paint file op GitHub?

**Comment by michielzyde96** [comment]
Merci, en ik had gedacht aan de eerste afbeelding dat je nog geen achievement hebt (blauw) en dat je voor brons aan het gaan bent (zie brons eerste cirkel), als je brons hebt behaalt wordt het icoon brons en de cirkel grijs omdat je voor grijs gaat en hetzelfde voor goud, snap je?

Dat met die text komt in orde  en voor SVG kan je dit instellen in Illustrator?

Het staat nog niet op Github, moet ik dit als png of als illustrator file erop plaatsen?

**Comment by HeinPauwelyn** [comment]
Zou je het er gewoon geen transparantie op zetten van 50% als je het nog niet behaald hebt? Nu lijkt het alsof er 4 statussen zijn.

<img src="https://cloud.githubusercontent.com/assets/16222780/21135295/b21508e2-c121-11e6-829b-a2b35b5ccfd7.png" align="left" width="350"/>

Vind idee van SO goed: enkel nog afbeeldingen en eigen details toevoegen. Indien progress bar is 100% gevuld, een zilveren badge is behaald en wordt het prosses voor een gouden badge getoond.
<br/><br/><br/><br/>

 
-------

Voor oplsaan als SVG, check: [Illustrator: How to export SVG](https://helpx.adobe.com/illustrator/how-to/export-svg.html). Weet wel niet als Android daarmee overweg kan...

**Comment by HeinPauwelyn** [comment]
Heb eens opgezocht text in SVG is blijkbaar dit:

```html
<!DOCTYPE html>
<html>
<body>
    <svg height="30" width="200">
        <text x="0" y="15" fill="black">I <tspan id="text"></tspan> SVG!</text>
        Sorry, your browser does not support inline SVG.
    </svg>

    <script>
        document.getElementById("text").innerHTML = "use";
    </script>
</body>
</html>
```

Kan je gemakkelijk met Angular een component aanmaken zodat je die code maar een keer hoeft te maken. Als het werkt tenminste...

**Comment by michielzyde96** [comment]
Zoals je kan zie heb ik enkele aanpassingen gedaan.
Om te beginnen zie je dat je bv voor brons aan het gaan bent (6/10 followed people)
Die progress zal te zien zijn en het zou tof zijn als je erop klikt, dat je dan de nog niet behaalde achievements (zie omcirkelt) kan zien, dus je weet dat je deze dan ook kan verdienen.

Indien je bronzen achievement behaalt dan krijg je die achievement en kan dit bij behaalde achievements gezet worden (idee).

Dan gaat de progres terug voort, nu ga je voor zilver en dan voor goud.

Snap je dit?

![image](https://cloud.githubusercontent.com/assets/23495460/21144593/938a5c40-c14b-11e6-950c-30dd39eb8145.png)

**Comment by ExCellRaD** [comment]
Ik vind het er goed uitzien. Wel als je nu een bronzen hebt, en dan begint de progress van de zilveren, heb je al 10/50 -> de progress cirkel is dan al een deel gevuld? Van zilver naar goud heb je al 50/100 -> cirkel is al halfvol direct als je zilver behaalt?

**Comment by michielzyde96** [comment]
Dat is inderdaad nog een issue, misschien kunnen we de aantallen verhogen ipv bij silver 50 followers naar 100 trekken en voor gold naar 250? Dan valt dit minder op? Ik zie niet direct een andere manier

**Comment by HeinPauwelyn** [comment]
1. Wat @ExCellRaD is inderdaad waar het moet exponentieel gaan met een factor x3.5 mss goed

    | Status       | Eis _Friends_ | Eis _Watcher_ |
    | :----------- | ------------: | ------------: |
    | **Brons**    | 10            | 5             |
    | **Zilver**   | 35            | 17            |
    | **Goud**     | 122           | 60            |

    Ik zou niet naar 250 gaan. Voor de reden dat het bijna onmogelijk is om 250 series te volgen die je wilt volgen. Merk ook op dat je voor _friends_ andere eisen kan gebruiken dan voor bv. _watcher_. De database is in dat geval perfect flexibel in.

2. Indien je al in de zilveren achievement behaald hebt, is het het onnodig voor nog te kunnen bewijzen dat je de bronzen achievement behaald hebt. Omdat je toch eerst brons moet winnen om daarna zilver te winnen

3. Ik zou ook niet de gouden achievement tonen indien je de bronzen nog niet hebt. Enkel een melding van _"Zilveren achievement: 10/35"_ (m.a.w. de volgende dus met progress in de cirkel), is voldoende.

**Voorbeeld:** Els is een nieuwe gebruiker en heeft nog nul achievements. Ze kan enkel het progress van de bronze achievements zien. Pas als ze de bronzen achievement _Follower_ gewonnen heeft, kan ze het progress van de zilveren achievement _Follower_ zien. Eens ze die wonnen heeft, dan kan ze het progress van de gouden achievement _Follower_ zien. Als ze dit gewonnen heeft is het spelletje ten einde.

Indien Els de gouden _Follower_ gewonnen heeft maar nog niet de zilveren _Watcher_ (ze heeft dus een bronzen _Watcher_) gewonnen heeft, kan ze de eisen voor de gouden _watcher_ nog niet zien, de zilveren progressie wel. Alles op zijn tijd, zeg ik dan.

**Comment by michielzyde96** [comment]
Komt in orde, maar ik heb gewoon alle afbeelding gemaakt he zodat je ze hebt, het is inderdaad niet de bedoeling om ze allemaal te tonen (zoals die goud als je nog maar brons hebt).

Ik wou gewoon alles in 1 keer maken zodat je alles hebt.
Ben nu nog bezig met een tracker achievement die bijhoudt hoeveel uren je kijkt.

Een friends achievement zal ik niet maken aangezien we met followers werken.

Dat met die eisen en factor x3.5 is toch ook niet echt zo goed? Aangezien je vb 11 mensen volgt heb je brons gekregen en dan staat de progress bar aan 3/10 gevuld (wat net NIET de bedoeling is).

Of bedoel je het niet zo?

**Comment by HeinPauwelyn** [comment]
eigenlijk niet nee. de factor 3.5 is gewoon voor de volgende achievement te berekenen op basis van de vorige afgerond naar het dichtstbijzijnde vijfvoud.

**Comment by michielzyde96** [comment]
Weet ik, dus 11 op 35 is ongeveer al 30% gevuld, wat @JasperDeSutter  wou zeggen is dat het niet de bedoeling is om al zoveel van je cirkel op te vullen

**Comment by HeinPauwelyn** [comment]
Anders is niet echt mogelijk vrees ik. Anders moet je de schaal nog groter maken maar dan is het nog moeilijker om goud te behalen.

**Comment by michielzyde96** [comment]
Ik zou het laten zoals het  is, Pokemon Go werkt ook zo haha

**Comment by HeinPauwelyn** [comment]
Ik denk het ook. Op SO is het ook zo eens je brons hebt is dat al ~30% van zilver. Touwens ben je van plan als de progressie van brons 10/10 is dit te tonen?

![image](https://cloud.githubusercontent.com/assets/16222780/21148391/5acf06a0-c158-11e6-9876-eaa08f2aea29.png)

Zou ik niet doen, ik zou direct de progressie van zilver tonen. Dit is dan direct 10/35.

**Comment by michielzyde96** [comment]
Dat was mijn eerste gedacht, maar dan kan je niet echt je badge van de 10/10 (brons) bekijken.

**Comment by HeinPauwelyn** [comment]
https://jsfiddle.net/s0rtmga0/1/
