### ISSUE TITLE
Series search

### ISSUE THREAD

**Issue by ExCellRaD** [WatchFriends/Web#6]

**Comment by ExCellRaD** [comment]
zit in api

**Comment by HeinPauwelyn** [comment]
ai vervelend... 😕

**Comment by HeinPauwelyn** [comment]
Ga opnieuw openen omdat we dat toch moeten hebben in de backend.

**Comment by HeinPauwelyn** [comment]
Momenteel naar TMDb, later aanpassen naar eigen API op backend en dat doe ik.

**Comment by HeinPauwelyn** [comment]
fixes #97
