### ISSUE TITLE
Achievements verkrijgen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#61]

**Comment by HeinPauwelyn** [comment]
Afhangelijk van:

| To do | Done |
| -- | -- | 
| <ul><li>#96</li><li>#105</li><li></li></ul> | <ul><li>#94</li><li>#57</li><li>#70</li> |

**Comment by HeinPauwelyn** [comment]
Ga me hiermee bezig houden

**Comment by ExCellRaD** [comment]
@HeinPauwelyn nog mee bezig?

**Comment by HeinPauwelyn** [comment]
Ja

**Comment by HeinPauwelyn** [comment]
@ExCellRaD Is nu af. Wil je PR #196 bekijken?
