### ISSUE TITLE
Lijsten van Homefragment van database halen en details van TMDb

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#63]
## Verandering

Static data in [`./data/serieslists.json`](https://github.com/WatchFriends/Web/blob/master/data/serieslists.json) en moet nu in de database staan en de details van TMDb halen. 

## To do

- [x] Data uitlezen
- [x] Data afhalen van TMDb zie PR #62 en issue #46
- [x] Data van database en TMDb samenvoegen zodat alles gegenvens kunnen doorgestuurd worden via de API.

## Referenties

- https://github.com/WatchFriends/Android/issues/105
- https://github.com/WatchFriends/Android/pull/114

**Comment by HeinPauwelyn** [comment]
Zit momenteel met volgend probleem: [Let Node wait till all data is loaded to send response][1]. Heb volgende reacties:

> Yes it's possible what you want, take a look to promises, or with async/await operators. [ponyfoo.com - understanding-javascript-async-await][2]<br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;– Hosar

> I would also suggest trying [async.js][3] <br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;– Gil Z 

Ik kies voor promises (denk ik 🤔 💭).

  [1]: http://stackoverflow.com/questions/41087504/let-node-wait-till-all-data-is-loaded-to-send-response
  [2]: https://ponyfoo.com/articles/understanding-javascript-async-await
  [3]: http://caolan.github.io/async/

**Comment by ExCellRaD** [comment]
Ik denk dat https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Promise/all een oplossing kan zijn.

**Comment by ExCellRaD** [comment]
Daarvoor moeten we wel databaseService en apiService met promises laten werken.

**Comment by HeinPauwelyn** [comment]
Dacht het ook al. Een andere suggestie vanop SO was [async.js](http://caolan.github.io/async/)

**Comment by HeinPauwelyn** [comment]
Dat is een goede oplossing... 

> I encountered a similar problem before, and got around it with something like 

> ```js
> if (seriesData.length == data[listIndex].series.length) { 
>     res.send(seriesData) 
> }
> ```

>The other comments suggesting using promises or async.js are almost certainly better ideas - I started to look at promises, but don't quite get it yet. If anyone can tell me whether my idea is any good or not, I'd be happy to learn. It worked for me in my case, but felt pretty hacky... – Runny Yolk

**Comment by HeinPauwelyn** [comment]
Eindelijk opgelost! zie gelijknamige PR: #64
