### ISSUE TITLE
Extra lijsten toevoegen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#74]
Lijsten zoals

- [x] _Today on TV_
- [ ] ~~_New_~~ &rarr; Er keert slechts één serie terug vanop TMDb en dat is te weinig
- [ ] _Maby intrested for you_ &rarr; op basis van gevolgde series
- [ ] _Recommend by friends_ &rarr; op basis van uw vrienden.

**Comment by HeinPauwelyn** [comment]
_Today on TV_ toegevoegd zie #75

**Comment by ExCellRaD** [comment]
Today on tv zou afhankelijk van de user een andere lijst moeten teruggeven. Vb: mensen van Vlaanderen zien wat er vandaag op TV is in Vlaanderen, maar niet in Duitsland. Ik zou ook kijken naar welke series de user volgt en die voorrang geven in de lijst.

**Comment by ExCellRaD** [comment]
Dit geldt eigenlijk voor bijna iedere lijst, daarmee dat ik dit niet een goede oplossing vind.

**Comment by HeinPauwelyn** [comment]
Oke dat is dan een feature voor later. Eerst moeten we data van de gebruikers hebben op de backend.

Als dit geld voor eidere lijst, dat weet ik zo niet. Een Belg kan ook naar bv. _Sturn der liebe_ kijken, een Duitse serie en vise versa.

**Comment by HeinPauwelyn** [comment]
_Today on TV_ kan ik idd later aanpassen.

**Comment by ExCellRaD** [comment]
Ja inderdaad, iedere gebruiker kan naar iets anders kijken, u is het hetzelfde voor iedereen. Maar je hebt wel gelijk dat we dan gebruikers moeten toevoegen.
Is Michiel daarmee bezig?

**Comment by HeinPauwelyn** [comment]
Nee Niels, maar heeft een probleem (zie: https://github.com/WatchFriends/Android/issues/143)

**Comment by HeinPauwelyn** [comment]
De lijsten _Maby intrested for you_ en _Recommend by friends_ zullen zeker voor iedereen afhankelijk zijn.

**Comment by HeinPauwelyn** [comment]
Ik kan ook lijsten aanmaken in de database bv. _German_, _Flemish_, _French_, _horror_, _SiFi_, _Kids_, _Comedy_, enz. en afhankelijk van de interesses (zijn gevolgde series enzo)_, enkele lijsten niet weergeven.

**Comment by HeinPauwelyn** [comment]
Waarom niet?

**Comment by HeinPauwelyn** [comment]
Of kan dat via een API van TMDb waar je at random enkele series uitpikt op basis van het geliefde genre van de gebuiker...

**Comment by ExCellRaD** [comment]
Ik zou inderdaad alle lijsten aanmaken op basis van de user, met eventueel willekeurige dingen, of met API van TMDb, het is specifiek per lijst natuurlijk.

**Comment by HeinPauwelyn** [comment]
Heb alles wat met database te maken heeft al weg gedaan incl. de collectie. zie commit: https://github.com/WatchFriends/Web/commit/51d59b8ab6c674fb8d3d82aa21645e81ada5c90d

**Comment by HeinPauwelyn** [comment]
Uw idee is trouwens ongeveer hetzelfde wat ik bedoelde hier:

> Ik kan ook lijsten aanmaken in de database bv. German, Flemish, French, horror, SiFi, Kids, Comedy, enz. en afhankelijk van de interesses (zijn gevolgde series enzo), enkele lijsten niet weergeven.

Het verschil is dat de items in de lijst vast zijn en dat alles opgeslaan wordt op onze database.

**Comment by ExCellRaD** [comment]
> dat de items in de lijst vast zijn

Dat is eigenlijk het grootste probleem ermee, alles moet ook manueel erin gestoken worden en het is veel minder schaalbaar. (dit is wat ik ook zei op de vorige PR  #66)
