### ISSUE TITLE
Auto deployment van site

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#84]
Wat kiezen we:

1. Telkens er een nieuwe release is?
2. Telkens als er een PR gesloten werd?

Opmerkingen: 

* Optie 1 is logischer.
* Optie 2 is gemakkelijker en hoef je niet te denken aan een nieuwe release te maken

**Comment by mickverm** [comment]
Ben voorstander van optie 2 eigenlijk, anders moet je wachten van een nieuwe feature te gebruiken in front-end of android tot dat er een release geweest is.

**Comment by ExCellRaD** [comment]
Same, iedere pull request is goed. Het is niet zo veel overbodig werk als het een keer te veel gebeurd.

**Comment by HeinPauwelyn** [comment]
> anders moet je wachten van een nieuwe feature te gebruiken

Hoeft niet na elke PR kan je zeggen dat er een nieuwe versie is. Je hebt `major.minor.release.build`. Indien typfouten of kuis kan je de release het nummer `0.2.3.1` geven. Momenteel nummer ik de `build` niet, enkel de `major.minor.release`
