### ISSUE TITLE
Database Model

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Web#85]
```json
{
	"_id": "",
	"userId": "",
	"following": [{
		"seriesId": 12,
		"seasons": [{
			"number": 1,
			"episodes": [{
				"1": true,
				"2": false,
				"3": true
			}]
		}, {
			"number": 2,
			"episodes": [{
				"1": true,
				"2": false
			}]
		}]
	}]
}
```

Is dit een goede database structuur?

**Comment by JasperDeSutter** [comment]
Naam van de tabel/schema?

**Comment by HeinPauwelyn** [comment]
Op eerste zicht oke maar waarom is `episodes` een array? Oke er zijn meerdere episodes in een seizoen maar dan zet je daar slechts één object in... Een beetje raar om daarvoor een object voor te maken niet?

Ik zou volgende doen:

```json
"episodes": [
    1,
    3,
    4
]
```

-----------------

Is volgende stelling juist?

> Je volgt een serie en je kan episodes markeren als bekeken of zal ik bekijken.

Indien ja, zou ik de structuur volledig overhooien als volgt: 

{
    "_id": "",
    "userId": "",
    "following": [ 45, 296, 5989, 5968 ], // --> enkel ID's van gevolgde series
    "watch": [
        "series": 45
        "seasons": [
            {
                "number": 1,
                "episodes": [
                    {
                        "number": 1,
                        "status": -1 // zie verder
                    }, {
                        "number": 3,
                        "status": 1 // zie verder
                    }
                ]
            }, {
                "number": 1,
                "episodes": [
                    {
                        "number": 1,
                        "status": -1 // zie verder
                    }, {
                        "number": 3,
                        "status": 1 // zie verder
                    }
                ]
            }
        ]
    ]
}
```

Een property zoals `1`, `2` of `3` zal niet lukken vrees ik omdat je niet weet hoeveel episodes er in een seizoen zijn en omdat je er niet over kunt loopen.

**Comment by JasperDeSutter** [comment]
Opmerkingen:
- Season.number -> seasonId 
- Afleveringen gewoon een lijst van nummers die je volgt
vb:
[1,3,4,7] -> enkel deze worden gevolgd.

**Comment by mickverm** [comment]
ik zou dan onder een seizoen nog meegeven hoeveel afleveringen er in zitten dan?
en ja een property zoals 1,2,3 had ik inderdaad over het hoofd gezien :P

**Comment by HeinPauwelyn** [comment]
Er kan een aflevering toegevoegd worden en dan is onze data mis.

**Comment by JasperDeSutter** [comment]
Hoezo? Nieuwe afleveringen krijgen een hoger nummer/id

**Comment by mickverm** [comment]
controleren en bijwerken indien nodig eh dan

ik wil de volgende te bekijken aflevering kunnen aanduiden
stel: seizoen x: 10 afleveringen
bekeken: 1,2,3,5,6,7,8,9,10

dan wil ik aan de user kunnen zeggen:
Missed episode: 4
Next episode: ofwel seizoen 2 episode 1 ofwel: geen volgende aflevering te bekijken

**Comment by HeinPauwelyn** [comment]
Oke maar ik zou **niet :-1: het aantal episodes opslaan** op onze eigen database.

**Stel:** Er is een seizoen met veel episodes in één seizoen zoals bv. Familie of Thuis _(Slecht voorbeeld want je hebt bijna geen data ervan)_. Er kunnen continue episodes ervan toegevoegd worden omdat bijna niemand weet hoeveel afleveringen er zullen uitgezonden worden in één seizoen.

:information_source: Hou ook rekening dat **TMDb een community site** :warning: is. De kans op fouten is reëel. als er een episode te veel staat, dan is onze data opnieuw verkeerd.

Ik zou dus iedere keer indien het nodig is het aantal episodes opvragen van TMDb om zo "correcte data" _(tussen aanhalingstekens)_ te hebben _(gelijklopende data is een beter woord i.p.v. correct)_. 

Ik zou idd ook **enkel de nummers** van een episode **bijhouden** incl. seizoen en serie. Indien er een ontbreekt kan dat zijn door:

- Gebruiker heeft het niet bekeken
- TMDb kent die episode niet _(er kunnen episodes ontbreken)_ :warning: 

Dat laatste kan je oplossen in de app. Later meer info _(zal niet in deze comment of issue zijn)_. Bij het eerste kan je idd een melding geven zoals jij zei :+1:

**Comment by mickverm** [comment]
Ok, zal deze feedback in het achterhoofd houden en beginnen aan het model en dergelijke

**Comment by HeinPauwelyn** [comment]
Waarom niet toevoegen aan de collectie users die er nu al is?

**Comment by mickverm** [comment]
Ben hier dus effectief aan bezig maar zit nog met enkele problemen die ik momenteel niet opgelost krijg, ben dus even verder aan het researchen

**Comment by ExCellRaD** [comment]
Als je met vragen zit, stel ze maar he. Wij hebben er al meer aan gewerkt dus we zullen je verder kunnen helpen.

**Comment by mickverm** [comment]
````json
{
    "_id" : ObjectId("58610c12fd44620ac8406ca0"),
    "password" : "",
    "email" : "",
    "series" : [ 
        {
            "seasons" : [],
            "_id" : ObjectId("586122052380162dd867c760"),
            "following" : true,
            "seriesId" : 1207
        }, 
        {
            "seasons" : [],
            "_id" : ObjectId("5861227c2380162dd867c761"),
            "following" : false,
            "seriesId" : 1207
        }
    ],
    "providers" : [],
    "name" : {
        "familyName" : "Vermeersch",
        "givenName" : "Michiel"
    },
    "__v" : 0
}
````

ik kan dus een serie object zonder problemen pushen naar de series array, maar ik vind niet hoe ik een series object kan bijwerken op basis van het seriesId

**Comment by ExCellRaD** [comment]
Misschien zou je dit beter oplossen met een aparte tabel (following series ofzo) en daar per object een user bijhouden. Je kan ze dan nog even gemakkelijk ophalen en pushen, maar het bijwerken wordt een stuk gemakkelijker.

**Comment by HeinPauwelyn** [comment]
:-1: Vond ik niet zo'n goed idee. Voor het aantal tabellen en relaties te verminderen is alles in één tabel beter.

**Comment by ExCellRaD** [comment]
Ja maar arrays in arrays in arrays worden wel veel minder gemakkelijk om mee te werken dan een betere database structuur. Een groot deel van de logica (arrays checken, updaten, elementen vergelijken...) moeten we dan zelf niet meer schrijven omdat het gewoon al in de database wordt opgelost.

**Comment by mickverm** [comment]
lang leve sql met tussentabellen >.<

**Comment by mickverm** [comment]
Het is gelukt, met dank aan stackoverflow

**Comment by HeinPauwelyn** [comment]
Om dit te vermijden

> Arrays in arrays in arrays worden wel veel minder gemakkelij

Kan je bv. werken met één array bv.

```json
"series": [
    {
        "seriesId": 45,
        "seasonId": 1,
        "episodeId": 1
    }, {
        "seriesId": 45,
        "seasonId": 1,
        "episodeId": 2
    }, {
        "seriesId": 45,
        "seasonId": 1,
        "episodeId": 3
    }, {
        "seriesId": 45,
        "seasonId": 1,
        "episodeId": 4
    }, {
        "seriesId": 45,
        "seasonId": 2,
        "episodeId": 1
    }, {
        "seriesId": 1157,
        "seasonId": 1,
        "episodeId": 1
    }
]
```

Kan je dan wel geen following boolean aan toevoegen...
