### ISSUE TITLE
Profiel pagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#96]
- [x] Achievement tonen
- [x] Gevolgde series
- [ ] API
- [x] Profiel foto
- [ ] Instellingen
- [x] Angular _(**Tip:** for lus)_

**Comment by michielzyde96** [comment]
Momenteel ben ik bezig met een profielpagina die je als bezoeker kan zien, of als gebruiker iemand anders zijn profiel. Daarmee dat instellingen pagina iets apart zal zijn.
Het ziet er nu zo uit: 
![image](https://cloud.githubusercontent.com/assets/23495460/21567814/8f89d780-ceaf-11e6-9cbb-467c1b245390.png)

Om de achievements te tonen had ik gedacht dat je kan drukken op achievements en dat dan de afbeeldingen van de achievements worden getoond in plaats van zijn watchlist.
@WatchFriends/frontend-webdevelopers Vinden jullie dat een goed idee of liever iets anders gehad? Zodat ik weet hoe ik het ga designen.

**Comment by HeinPauwelyn** [comment]
Oke mss ken je nog een label naast de titel zetten met het aantal achievements of series in de watchlist. Een beetje zoals dit:

![image](https://cloud.githubusercontent.com/assets/16222780/21568106/f86eaae4-ceb1-11e6-8a8f-8f32ec1081c3.png)

**Comment by michielzyde96** [comment]
Goed idee, hoe zou ik de achievements tonen?

**Comment by HeinPauwelyn** [comment]
Drie naast elkaar met logo, juiste kleur, titel en eis. niet behaalde achievements zou ik niet tonen. Indien er nog geen achievemnts gewonnen zijn:

> Follow and watch your series or friends to collect achievements.

**Comment by HeinPauwelyn** [comment]
Wat is je laatste commit? Ga naar de client en zoek laatste commit en klik op de link `GitHub` en plaats die url in een comment. Wil eens je code bekijken.

![image](https://cloud.githubusercontent.com/assets/16222780/21568388/617ab490-ceb4-11e6-8dc8-178ccbcf7357.png)

**Comment by HeinPauwelyn** [comment]
Hoe plaats je de series op je profiel data is dat nog static HTML?

**Comment by michielzyde96** [comment]
Data is nog static, @ExCellRaD ging zich daarmee bezig houden met die API, hadden we zo afgesproken.

**Comment by michielzyde96** [comment]
@HeinPauwelyn dit is de link https://github.com/WatchFriends/Web/commit/4b596a8065d4bad3ab5e94cb754580328a49a031

**Comment by HeinPauwelyn** [comment]
Kan je dat niet nu al aanpassen zoals @ExCellRaD het al gedaan heeft op de explorer pagina: https://github.com/WatchFriends/Web/blob/master/frontend/app/explore/explore.component.html en https://github.com/WatchFriends/Web/blob/master/frontend/app/explore/explore.component.ts.

**Comment by michielzyde96** [comment]
Komt in orde!

**Comment by michielzyde96** [comment]
Kan er iemand aan verderwerken? Ik heb vandaag geen tijd meer. Volgende implementatie zou moeten gebeuren: 

als je klikt op achievements, dan krijg je deze te zien met alle details, bij hover zie je de eis (followed 6 people). De achievement titel wordt dan de active class en de my watchlist title wordt dan aanklikbaar. Je moet dus kunnen switchen tussen 2 menus binnen 1 pagina.

![image](https://cloud.githubusercontent.com/assets/23495460/21577190/8d3e190c-cf52-11e6-99d6-717737d902d0.png)

**Comment by HeinPauwelyn** [comment]
Ik zou niet bij een hover doen want dan sluit je een deel van de gebruikers uit. Dit zijn vooral mensen die geen muizen gebruiken maar bv. screenreaders of de <kbd>tab</kbd> toets.

Uw idee in #59 was goed. Niet behaalde achievements worden niet getoond.

![][1]

------------

Heb vandaag wel een gaatje. Ben toch nog aan het nadenken hoe ik het zal doen met de tokens. Dit zal voor na nieuwjaar zijn.

  [1]: https://cloud.githubusercontent.com/assets/16222780/21136176/d88ce794-c124-11e6-9ddc-8c2b68b6583a.png

**Comment by HeinPauwelyn** [comment]
![image](https://cloud.githubusercontent.com/assets/16222780/21578471/90e2ff30-cf81-11e6-9187-6126b05f4f23.png)

**Comment by HeinPauwelyn** [comment]
@WatchFriends/frontend-webdevelopers Weten jullie een antwoord op deze vraag? [Prevent adding attribute selectors to SaSS selectors with angular 2](http://stackoverflow.com/questions/41415293/prevent-adding-attribute-selectors-to-sass-selectors-with-angular-2) van op Stack Overlow?

**Comment by michielzyde96** [comment]
Iemand die mij kan helpen? Ik had daarnet gemergd met de master en er waren een heel aantal conflicten die ik opgelost heb maar nu werkt npm start niet meer: 
![image](https://cloud.githubusercontent.com/assets/23495460/21582198/79b0f0ce-d04e-11e6-8026-fd7ae03a0772.png)

**Comment by michielzyde96** [comment]
Dit waren de conflicten: 
![image](https://cloud.githubusercontent.com/assets/23495460/21582212/ba6989a0-d04e-11e6-915e-d3d3d619fc24.png)

**Comment by JasperDeSutter** [comment]
De error zegt dat hij services/server-error.ts niet vindt.

**Comment by michielzyde96** [comment]
Ik heb geen server-error.ts , van waar haal je dat?

**Comment by JasperDeSutter** [comment]
Master branch.

**Comment by HeinPauwelyn** [comment]
Rtfe

**Comment by HeinPauwelyn** [comment]
- [ ] Nog een kleine bug dat nog opgestost moet worden maar denk dat dit tegen vanmiddag af zal zijn. 

- [x] Heb trouwens ook nog een paar andere dingen aangepast. Zo is de SaSS en HTML code voor de watchlist en die submenu waar _watchlist_ en _achievements_ nu identiek met de explorer page. Qua herbruikbaarheid is dit zeer goed en de puntjes 💯. Heb ook nog de data gelijk gezet met hoe ik het denk dat het van de database zal komen.

- [x] SVG code staat nu inline met de HTML code. Deze heb ik express gedaan zodat je nog enkel de outer tag een klasse moet geven. vb.

    ```html
    <div class="brons">
        <svg><path/><svg>
    </div>
    <div class="silver">
        <svg><path/><svg>
    </div>
    ```

    ```css
    .brons {
      fill: #D1A684;
    }
    .silver {
      fill: #B4B8BC;
    } 
    .gold {
      fill: #FFCC01;
    }
    ```

    Nu hoeven we enkel nog die klasse aan te passen terwijl de image hetzelfde blijft.

- [ ] Straks nog het gene dat @ExCellRaD heeft aangeraden omterent die pipes _(zie comment in commit https://github.com/WatchFriends/Web/commit/121931db5b73842ef02a928ffadc9ee1f1e9202d)_.

-------------

**P.S. @michielzyde96:** Ik heb vermoeden dat uw branch onstabiel is. Wil je graag een nieuwe branch aanmaken? Zo heb je in het vervolg minder problemen.

**Comment by HeinPauwelyn** [comment]
Waarom staat instellingen ook in de to do lijst? Zou het niet beter zijn om daarvoor een apparte pagina aan te maken?

**Comment by ExCellRaD** [comment]
@michielzyde96 de settings komen dus op en aparte pagina he?

**Comment by michielzyde96** [comment]
@ExCellRaD ja, ik voorzie een knop op de profiel pagina die zal doorverwijzen naar de eigen settings.
