### ISSUE TITLE
Search Pagina

### ISSUE THREAD

**Issue by michielzyde96** [WatchFriends/Web#97]
Deze pagina zal hetzelfde design hebben als de series pagina maar dan kan je wisselen tussen gezochte series of personen.

To Do: 

- [x] Series Tonen
- [x] Personen Tonen
- [ ] API search function 
- [x] Responsive

**Comment by HeinPauwelyn** [comment]
fixes #6

**Comment by JasperDeSutter** [comment]
@michielzyde96 kan je dit eerst afwerken voordat je aan een volgend scherm begint?

**Comment by michielzyde96** [comment]
@JasperDeSutter is eigenlijk hetzelfde als de explorer pagina, gesearchde series worden getoond en ook nog personen.
